version: "3.8"

services:
  chrom-b:
    build:
      context: .
      args:
        UID: "${UID}"
        GID: "${GID}"
    container_name: chrom-b

    user: "${UID}:${GID}"
    # Keep the container alive without producing logs:
    entrypoint: []                  # neutralize any ENTRYPOINT from the image
    # entrypoint: ["/bin/sh","-lc","safe-third-party; exec sleep infinity"]
    command: [
      "sleep",
      "infinity",
    ]  # long-running no-op
    restart: unless-stopped         # stays up across reboots unless you stop it
    working_dir: /chromium
    volumes:
      - /home/juagargi/devel/ETH/chromium:/chromium
      - /home/juagargi/devel/depot_tools:/depot_tools
    environment:
      - PATH=/depot_tools:$PATH
